"""added new fields in Customer table

Revision ID: 547f5907df74
Revises: 7f56b8462798
Create Date: 2023-09-12 21:33:57.138441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '547f5907df74'
down_revision = '7f56b8462798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('contact', sa.String(length=12), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('contact')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
