"""customer table orders table with update field

Revision ID: 7f56b8462798
Revises: 1daceb6031ce
Create Date: 2023-09-11 21:36:12.406661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f56b8462798'
down_revision = '1daceb6031ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_updated'), ['updated'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_updated'))
        batch_op.drop_column('updated')

    # ### end Alembic commands ###
