name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      OAUTH2_CLIENT_ID: ${{secrets.OAUTH2_CLIENT_ID}}
      OAUTH2_CLIENT_SECRET: ${{secrets.OAUTH2_CLIENT_SECRET}}
      OAUTH2_META_URL: ${{secrets.OAUTH2_META_URL}}
      CONFIG_MODE: ${{secrets.CONFIG_MODE}}

    services:
        postgres:
          image: postgres:latest  # Use the PostgreSQL version you need
          env:
            POSTGRES_USER: testuser
            POSTGRES_PASSWORD: testpass
            POSTGRES_DB: orders_api_db_test
          ports:
            - 5432:5432  # Map the PostgreSQL port
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in $(seq 1 30); do
            pg_isready -h localhost -p 5432 -U testuser && break
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5
          done

      - name: Run tests
        run: | 
          pytest

  build:
      name: Heroku Deploy
      needs: test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: akhileshns/heroku-deploy@v3.12.14
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "jimmie-orders-api"
            heroku_email: "jimmiemunyi@gmail.com"